--Procedure tao User cho cac nhan vien trong bang NhanVien v?i password c?ng là maNV
CREATE OR REPLACE PROCEDURE CREATE_USER 
AS
  CURSOR TBL_NV  IS SELECT maNV FROM NhanVien ;
BEGIN
  FOR ROW_NV in TBL_NV 
  LOOP 
  EXECUTE IMMEDIATE 'CREATE USER ' || ROW_NV.maNV || 'IDENTIFIED BY' || ROW_NV.maNV;
  EXECUTE IMMEDIATE 'GRANT CONNECT TO' || ROW_NV.maNV;
  END LOOP;
END;
EXECUTE CREATE_USER ;
